services:
  mysql:
    image: mysql
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=26632764
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=26632764